```{r}
################################################################################
# Create matrix with constant, additive and multiplicative structure
################################################################################
library(gplots)
#Matrix characteristics
rows = 100
cols = 100
cluster_size = 25
background_signal = 100
background_signal_sd = 20
noise_sd = 5

set.seed(1)
#Create matrix with background signal
df <- matrix(rnorm(rows*cols,background_signal,background_signal_sd),rows,cols)

#Create and add constant structure
res = 50
df[1:cluster_size,1:cluster_size] <- res

#Create and add additive structure
res = c()
row = c(rnorm(cluster_size, 150,25))
  for (j in 1:cluster_size) {
    res = cbind(res, row+rnorm(1,0,25))
  }
df[(cluster_size+1):(2*cluster_size),(cluster_size+1):(2*cluster_size)] <- res

#Create and add multiplicative structure
res = c()
row = c(rnorm(cluster_size, 50,25))
  for (j in 1:cluster_size) {
    res = cbind(res, row*abs(rnorm(1, 1, 0.25)))
  }

df[(nrow(df)-cluster_size+1):nrow(df),(ncol(df)-cluster_size+1):ncol(df)] <- res

#Add noise
df <- df + rnorm(rows*cols,0,noise_sd)

#Create heatmap
heatmap.2(df,dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none')
```

```{r}
source("functions_GA_full.R")
################################################################################
# Code to run the Algorithm
################################################################################
# Genetic algorithm parameters  ------------------------------------------------
solution_size <- nrow(df)+ncol(df)
cluster_types <- rep(c("shifting", "scaling"),4)
cluster_type <- c()

#Maximum amount of SCs to be retrieved
iters <- 10
set.seed(1)

#Applying the algorithm
GA_SC(df, cluster_types = cluster_types, iters = iters)
```

```{r}
# Import functions for simulation study  ---------------------------------------
source("functions_clusters.R")
library(gplots)
library(tidyverse)
library(biclust) #For Plaid and Bimax
library(fabia) #For Fabia
library(isa2) #For Isa
```

```{r}
################################################################################
# Constant SCs
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3 #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = c(150,50,150) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength

iters <- 10

number_of_datasets = 25

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("constant"),6)
cluster_type <- c()

# Bicluster Algorithm ----------------------------------------------------------
result <- c()
Sys.time()
for (i in 1:number_of_datasets){
  tryCatch({
seed <- sample(1:1000,1)
set.seed(seed)

#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Constant cluster
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "constant")

for (j in 1:3){
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

result <- rbind(result, c(cluster_error(cluster_list, GA_list),seed,cluster(df)))
}
  }, error=function(error_message){
    message(error_message)
  })
}
Sys.time()

result
```
```{r}
################################################################################
# Additive SCs
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3 #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = c(150,50,150) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength
#For shifting clusters
shift = rep(25,cluster_count)
shift_noise = 0

iters <- 10

number_of_datasets = 25

# GA settings ------------------------------------------------------------------
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("shifting"),6)

result <- c()

Sys.time()
for (i in 1:number_of_datasets){
  tryCatch({
seed <- sample(1:1000,1)
set.seed(seed)
#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Shifting clusters columns only ---------------------------------------------
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "shift", shift, shift_noise)

for (j in 1:3){
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

result <- rbind(result, c(cluster_error(cluster_list, GA_list),seed,cluster(df)))
}
  }, error=function(error_message){
    message(error_message)
  })
}
Sys.time()

result
```
```{r}
################################################################################
# Multiplicative SCs
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3 #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = c(150,50,150) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength
#For scaling pattern
scale = rep(1,cluster_count)
scale_noise = rep(0.5,cluster_count)

iters <- 10

number_of_datasets = 25

# GA settings ------------------------------------------------------------------
cluster_types <- rep(c("scaling"),6)
result <- c()

result <- c()
Sys.time()
for (i in 1:number_of_datasets){
  tryCatch({
seed <- sample(1:1000,1)
set.seed(seed)
#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Scaling clusters -------------------------------------------------------------
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "scale", scale, scale_noise)

for (j in 1:3){
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

result <- rbind(result, c(cluster_error(cluster_list, GA_list),seed,cluster(df)))
}
  }, error=function(error_message){
    message(error_message)
  })
}
Sys.time()

result
```

```{r}
################################################################################
# Constant, Additive, Multiplicative SCs
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3 #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = c(150,50,150) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength
#For shifting clusters
shift = 25
shift_noise = 0
#For scaling pattern
scale = 1
scale_noise = 0.5

# GA settings ------------------------------------------------------------------
cluster_types <- rep(c("shifting", "scaling"),3)
cluster_type <- c()

result <- c()
Sys.time()
for (i in 1:25){
  tryCatch({
seed <- sample(1:1000,1)
set.seed(seed)

#Add noise
df <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow,ncol)

#Add constant cluster
res = signal[1]

df[1:cluster_x,1:cluster_y] <- res

#Add shifting cluster
res = c()
row = c(rnorm(cluster_x, signal[2],shift))
  for (j in 1:cluster_y) {
    res = cbind(res, row+rnorm(1,0,shift))
  }

df[(cluster_x+1):(2*cluster_x),(cluster_y+1):(2*cluster_y)] <- res

#Add scaling cluster
res = c()
row = signal[3] * rnorm(cluster_x, scale, scale_noise)
  for (j in 1:cluster_y) {
    res = cbind(res, row*abs(rnorm(1, scale, scale_noise)))
  }

df[(nrow(df)-cluster_x+1):nrow(df),(ncol(df)-cluster_y+1):ncol(df)] <- res

#Add some noise
df <- df + rnorm(nrow*ncol,0,5)

#Save clusters
cluster_list[[1]] <- df[1:cluster_x,1:cluster_y]
cluster_list[[2]] <- df[(cluster_x+1):(2*cluster_x),(cluster_y+1):(2*cluster_y)]
cluster_list[[3]] <- df[(nrow(df)-cluster_x+1):nrow(df),(ncol(df)-cluster_y+1):ncol(df)]

for (j in 1:3){
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters)

result <- rbind(result, c(cluster_error(cluster_list, GA_list),seed,cluster(df)))
}
  }, error=function(error_message){
    message(error_message)
  })
}
Sys.time()

result
```
```{r}
################################################################################
# Effect of CLUSTER NUMBER
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_counts = c(1,2,3,4,5) #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = rep(150,5) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength

iters <- 10

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("constant"),6)
cluster_type <- c()

# Bicluster Algorithm ----------------------------------------------------------
result <- c()
Sys.time()
for (factor in 1:length(cluster_counts)){
cluster_count <- cluster_counts[factor]
for (i in 1:5){

seed <- sample(1:1000,1)
set.seed(seed)

#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Constant cluster
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "constant")

for (j in 1:3){
tryCatch({
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

result <- rbind(result, c(cluster_error(cluster_list, GA_list),seed,cluster(df),factor))
  }, error=function(error_message){
    message(error_message)
  })
  }
  }
}
Sys.time()

result
```
```{r}
################################################################################
# Effect of CLUSTER SIZE
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 1  #number of biclusters
clusters_x = c(5,10,20,40) #rows of bicluster
clusters_y = c(10,20,40,80) #columns of bicluster
signal = rep(150,3) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength

iters <- 10

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("constant"),6)
cluster_type <- c()

# Bicluster Algorithm ----------------------------------------------------------
result <- c()
Sys.time()
for (factor in 1:length(clusters_x)){
cluster_x <- clusters_x[factor]
cluster_y <- clusters_y[factor]
for (i in 1:5){

seed <- sample(1:1000,1)
set.seed(seed)

#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Constant cluster
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "constant")

for (j in 1:3){
tryCatch({
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

result <- rbind(result, c(cluster_error(cluster_list, GA_list),seed,cluster(df),factor))
  }, error=function(error_message){
    message(error_message)
  })
  }
  }
}
Sys.time()

result
```
```{r}
################################################################################
# Effect of BACKGROUND SIGNAL (shifting SCs)
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3  #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = rep(150,3) #Signal strength
background_signal = 100
background_noises = c(5,10,25,50)#noise strength
signal_noise =  5 #noise strength
#For shifting clusters
shift = rep(25,cluster_count)
shift_noise = 0

iters <- 10

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("shifting"),6)
cluster_type <- c()

# Bicluster Algorithm ----------------------------------------------------------
result <- c()
Sys.time()
for (factor in 1:length(background_noises)){
background_noise <- background_noises[factor]
for (i in 1:5){

seed <- sample(1:1000,1)
set.seed(seed)

#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Constant cluster
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "shift", shift, shift_noise)

for (j in 1:3){
tryCatch({
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

result <- rbind(result , c(cluster_error(cluster_list, GA_list),seed,cluster(df),background_noise))
  }, error=function(error_message){
    message(error_message)
  })
  }
  }
}
Sys.time()

result
```
```{r}
################################################################################
# Effect of NOISE
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3  #number of biclusters
cluster_x = 10 #rows of bicluster
cluster_y = 20 #columns of bicluster
signal = rep(150,3) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noises =  c(1,5,10,15) #noise strength

iters <- 10

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("constant"),6)
cluster_type <- c()

# Bicluster Algorithm ----------------------------------------------------------
result <- c()
Sys.time()
for (factor in 1:length(signal_noises)){
signal_noise <- signal_noises[factor]
for (i in 1:5){

seed <- sample(1:1000,1)
set.seed(seed)

#Background noise
noise <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow = nrow, ncol = ncol)

# Constant cluster
df <- add_clusters(noise, cluster_count, cluster_x, cluster_y, signal, signal_noise, randomize = F, type = "constant")

for (j in 1:3){
tryCatch({
res <- c(0,0)
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)
  
res <- c(cluster_error(cluster_list, GA_list))

result <- rbind(result , c(res,seed,cluster(df),signal_noise))
  }, error=function(error_message){
    message(error_message)
  })
  }
  }
}
Sys.time()

result
```

```{r}
################################################################################
# Effect of NON-EXCLUSIVITY
################################################################################
# Dataset Variables ------------------------------------------------------------
nrow <- 50 #number of rows
ncol <- 100 #number of columns
cluster_count = 3  #number of biclusters
cluster_x = 10
cluster_y = 20
signal = c(140,150,160) #Signal strength
background_signal = 100
background_noise = 25 #noise strength
signal_noise =  5 #noise strength
overlaps <- c(0.1,0.2,0.3,0.4)

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("constant"),6)
cluster_type <- c()

# Bicluster Algorithm ----------------------------------------------------------
result <- c()
Sys.time()
for (factor in 1:length(overlaps)){
overlap <- overlaps[factor]
for (i in 1:5){

seed <- sample(1:1000,1)
set.seed(seed)

#Add noise
df <- matrix(rnorm(nrow*ncol,background_signal,background_noise),nrow,ncol)

#Add constant cluster
df[1:cluster_x,1:cluster_y] <- signal[1]

df[((cluster_x+1)-round(cluster_x*overlap)):((2*cluster_x)-round(cluster_x*overlap)),(cluster_y+1):(2*cluster_y)] <- signal[2]

df[(nrow(df)-cluster_x+1):nrow(df),((2*cluster_y+1)-round(cluster_y*overlap)):((3*cluster_y+1)-round(cluster_y*overlap))] <- signal[3]

#Add some noise
df <- df + rnorm(nrow*ncol,0,5)

#Save clusters
cluster_list[[1]] <- df[1:cluster_x,1:cluster_y]
cluster_list[[2]] <- df[((cluster_x+1)-round(cluster_x*overlap)):((2*cluster_x)-round(cluster_x*overlap)),(cluster_y+1):(2*cluster_y)]
cluster_list[[3]] <- df[(nrow(df)-cluster_x+1):nrow(df),((2*cluster_y+1)-round(cluster_y*overlap)):((3*cluster_y+1)-round(cluster_y*overlap))]

#Create heatmap
heatmap.2(df,dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none')

for (j in 1:3){
tryCatch({
res <- c(0,0)
#Applying GA function
GA_list <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)
  
res <- c(cluster_error(cluster_list, GA_list))

result <- rbind(result , c(res,seed,cluster(df),overlap))
  }, error=function(error_message){
    message(error_message)
  })
  }
  }
}
Sys.time()

result
```
```{r}
################################################################################
# Load real life data set (Tomato data)
################################################################################
#Load tomato df
df_tomato <- readxl::read_xlsx("tomato_metabolite_sensory_data.xlsx")

#Remove labels
df_tomato <- scale(df_tomato[,-1])

heatmap.2(as.matrix(df_tomato),dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none')

df <- df_tomato

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 100
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("shifting", "scaling"),4)
cluster_type <- c()

iters <- 10

set.seed(1)
Sys.time()
#Applying GA function
tomato_res <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters, stop_pval = 0.01)

tomato_res
Sys.time()
```
```{r}
################################################################################
# Load real life data set (Alzheimer data)
################################################################################
load("AIDATA.Rdata")

df_alzheimer <- scale(t(ADmetabolites))

df_alzheimer <- df_alzheimer[c(which(sampleInfo[,2] == "Class 1"),which(sampleInfo[,2] == "Class 2")),]
heatmap.2(as.matrix(df_alzheimer),dendrogram='none', Rowv=FALSE, Colv=FALSE,trace='none')

df <- df_alzheimer
cluster_type <- c()

# GA settings ------------------------------------------------------------------
rows <- nrow(df)
cols <- ncol(df)
num_generations <- 500
pop_size <- 200
solution_size <- rows+cols
mutation_ratio <- 0.01 # Chance of mutation per byte
selection_ratio <- 0.5 # Ratio of best solutions that are used to create the next generation
zero_ratio <- 0.5 # Ratio of 0's in the initial population
elitism <- 2 # Number of best solutions that are kept unaltered
cross_over <- "uniform"
cluster_types <- rep(c("shifting","scaling"),4)
iters <- 10

set.seed(1)
Sys.time()
#Applying GA function
alzheimer_res <- GA_SC(df, num_generations, pop_size, mutation_ratio, selection_ratio, zero_ratio, elitism, cross_over, cluster_types, iters , stop_pval = 0.01)
Sys.time()

alzheimer_res
```

